FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc

COPY . /repo
WORKDIR /repo
RUN mkdir -p /install/bin
RUN make -j8
RUN make install PREFIX=/install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
